### ISSUE TITLE
Error with mail config when using web form certificate request (from slack)

### ISSUE THREAD

**Issue by kimdhamilton** [blockchain-certificates/cert-viewer#43]
Using the cert-viewer, when I try to request a certificate I get:

```￼2016-12-02 15:23:18,124 - root - ERROR - Unhandled Exception: __init__() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/home/kostas/crypto/blockcerts/venv/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kostas/crypto/blockcerts/venv/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kostas/crypto/blockcerts/cert-viewer/cert_viewer/views.py", line 236, in request_page
    sent = Notifier.factory().notify(
  File "/home/kostas/crypto/blockcerts/cert-viewer/cert_viewer/notifier.py", line 12, in factory
    return Mail()
TypeError: __init__() takes exactly 2 arguments (1 given)```

This comes up only with notifier 'mail'. 'noop' works and logs things fine. I have a mandrill account and have setup the api_key.

Any ideas? (edited)

[5:31]  
Btw, viewing and validating worked fine

[5:34]  
FYI, using the default links and instructions to use the docker image gets compose version 1.5.2 (on ubuntu 16.04)... while I believe 1.8.0 is needed? I didn't bother to install 1.8.0 to test since I installed mongodb locally and didn't use docker at all. Just letting you know.

**Comment by kimdhamilton** [comment]
Fixed with a58c9b8516b6897ecca84182e23b5dd5e337ed8b
