### ISSUE TITLE
docker.auth.auth.load_config: File doesn't exist

### ISSUE THREAD

**Issue by moorthi07** [blockchain-certificates/cert-viewer#53]
Error: 
docker-compose --verbose build  
-----------

compose.config.config.find: Using configuration files: .\docker-compose.yml

docker.auth.auth.load_config: File doesn't exist

Traceback (most recent call last):

 File "<string>", line 3, in <module>

 File "compose\cli\main.py", line 61, in main

 File "compose\cli\main.py", line 110, in perform_command

 File "compose\cli\command.py", line 35, in project_from_options

 File "compose\cli\command.py", line 110, in get_project

 File "compose\cli\command.py", line 85, in get_client

 File "site-packages\docker\api\daemon.py", line 76, in version

 File "site-packages\docker\utils\decorators.py", line 47, in inner

 File "site-packages\docker\client.py", line 140, in _get

 File "site-packages\requests\sessions.py", line 477, in get

 File "site-packages\requests\sessions.py", line 465, in request

 File "site-packages\requests\sessions.py", line 573, in send

 File "site-packages\requests\adapters.py", line 415, in send

requests.exceptions.ConnectionError: ('Connection aborted.', error(10061, 'No connection could be made because the target machine actively refused it'))

docker-compose returned -1

docker.auth.auth.load_config: File doesn't exist

**Comment by kimdhamilton** [comment]
this looks like a docker-compose connection error. Look at these threads:

- https://github.com/docker/machine/issues/3163
- https://github.com/docker/compose/issues/2495

My guess is either the proxy or env var problems mentioned in those threads.

**Comment by rdearman** [comment]
Problem is it lost the configuration, but how do you recreate it?

**Comment by kimdhamilton** [comment]
Please try the tips mentioned in the thread. This is a docker setup/configuration issue not specific to this project.
