### ISSUE TITLE
invalid syntax error "async=False" in notifier.py

### ISSUE THREAD

**Issue by hafsahabib-educator** [blockchain-certificates/cert-viewer#75]
i am running this in docker and getting invalid syntax error. i have made the line with error bold.
Thank you in advance.

below is my command history
`C:\Users\Hafsah\Documents\Python_Scripts\cert-viewer>docker-compose build
mongodb uses an image, skipping
Building web
Step 1/11 : FROM python:3
 ---> 825141134528
Step 2/11 : MAINTAINER Kim Duffy "kimhd@mit.edu"
 ---> Using cache
 ---> 4cf73eb8cb9a
Step 3/11 : WORKDIR /cert-viewer
 ---> Using cache
 ---> d09451c4cbe5
Step 4/11 : COPY /conf_local.ini /cert-viewer/conf.ini
 ---> Using cache
 ---> d0125acc9aa8
Step 5/11 : COPY requirements.txt /cert-viewer/
 ---> Using cache
 ---> 4f05954f9de1
Step 6/11 : COPY run.py /cert-viewer/
 ---> Using cache
 ---> 33fb9a21af25
Step 7/11 : RUN pip install -r /cert-viewer/requirements.txt
 ---> Using cache
 ---> 72b7e23aff00
Step 8/11 : ADD . /cert-viewer
 ---> 10b5921df475
Step 9/11 : ADD cert_data /etc/cert_data
 ---> 4a5494aa81c1
Step 10/11 : EXPOSE 5000
 ---> Running in 3203d88de1f7
Removing intermediate container 3203d88de1f7
 ---> 31fba5cce8c1
Step 11/11 : CMD ["python", "/cert-viewer/run.py"]
 ---> Running in cac22f5ea22f
Removing intermediate container cac22f5ea22f
 ---> 362d41b7f875
Successfully built 362d41b7f875
Successfully tagged blockcerts/certviewer:latest

C:\Users\Hafsah\Documents\Python_Scripts\cert-viewer>docker-compose up
cert-viewer_mongodb_1 is up-to-date
Recreating cert-viewer_web_1 ... done
Attaching to cert-viewer_mongodb_1, cert-viewer_web_1
mongodb_1  | 2018-08-07T04:27:09.813+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=7e9953f29ee5
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] db version v4.0.0
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] OpenSSL version: LibreSSL 2.7.4
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] allocator: system
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] modules: none
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] build environment:
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongodb_1  | 2018-08-07T04:27:09.828+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "0.0.0.0" } }
mongodb_1  | 2018-08-07T04:27:09.829+0000 I STORAGE  [initandlisten]
mongodb_1  | 2018-08-07T04:27:09.829+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongodb_1  | 2018-08-07T04:27:09.829+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongodb_1  | 2018-08-07T04:27:09.829+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=478M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongodb_1  | 2018-08-07T04:27:11.339+0000 I STORAGE  [initandlisten] WiredTiger message [1533616031:339696][1:0x7f6da4f30960], txn-recover: Set global recovery timestamp: 0
mongodb_1  | 2018-08-07T04:27:11.395+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongodb_1  | 2018-08-07T04:27:11.476+0000 I CONTROL  [initandlisten]
mongodb_1  | 2018-08-07T04:27:11.476+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongodb_1  | 2018-08-07T04:27:11.476+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongodb_1  | 2018-08-07T04:27:11.476+0000 I CONTROL  [initandlisten]
mongodb_1  | 2018-08-07T04:27:11.476+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 0200eee2-6cfd-4359-a46d-526f92e8a384
mongodb_1  | 2018-08-07T04:27:11.693+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
mongodb_1  | 2018-08-07T04:27:11.696+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 1db37355-a854-4601-bc9f-c4ea6e8943db
mongodb_1  | 2018-08-07T04:27:11.737+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongodb_1  | 2018-08-07T04:27:11.739+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongodb_1  | 2018-08-07T04:27:11.739+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 95708d55-290b-42cf-adf3-a1d4afb914c8
mongodb_1  | 2018-08-07T04:27:11.910+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
mongodb_1  | 2018-08-07T04:27:11.911+0000 I INDEX    [LogicalSessionCacheRefresh]        building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-08-07T04:27:11.913+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-08-07T04:27:11.914+0000 I COMMAND  [LogicalSessionCacheRefresh] command config.$cmd command: createIndexes { createIndexes: "system.sessions", indexes: [ { key: { lastUse: 1 }, name: "lsidTTLIndex", expireAfterSeconds: 1800 } ], $db: "config" } numYields:0 reslen:114 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { W: 1 } }, Collection: { acquireCount: { w: 1 } } } protocol:op_msg 175ms
mongodb_1  | 2018-08-07T04:27:12.780+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:34362 #1 (1 connection now open)
mongodb_1  | 2018-08-07T04:27:12.783+0000 I NETWORK  [conn1] received client metadata from 172.18.0.3:34362 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.93-linuxkit-aufs" }, platform: "CPython 3.7.0.final.0" }
mongodb_1  | 2018-08-07T04:27:13.854+0000 I NETWORK  [conn1] end connection 172.18.0.3:34362 (0 connections now open)
mongodb_1  | 2018-08-07T07:20:32.649+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:34364 #2 (1 connection now open)
mongodb_1  | 2018-08-07T07:20:32.680+0000 I NETWORK  [conn2] received client metadata from 172.18.0.3:34364 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.93-linuxkit-aufs" }, platform: "CPython 3.7.0.final.0" }
mongodb_1  | 2018-08-07T07:20:34.343+0000 I NETWORK  [conn2] end connection 172.18.0.3:34364 (0 connections now open)
mongodb_1  | 2018-08-07T07:26:19.880+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:34366 #3 (1 connection now open)
mongodb_1  | 2018-08-07T07:26:19.897+0000 I NETWORK  [conn3] received client metadata from 172.18.0.3:34366 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.93-linuxkit-aufs" }, platform: "CPython 3.7.0.final.0" }
mongodb_1  | 2018-08-07T07:26:21.560+0000 I NETWORK  [conn3] end connection 172.18.0.3:34366 (0 connections now open)
mongodb_1  | 2018-08-07T07:31:59.955+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:34368 #4 (1 connection now open)
mongodb_1  | 2018-08-07T07:31:59.957+0000 I NETWORK  [conn4] received client metadata from 172.18.0.3:34368 conn4: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.93-linuxkit-aufs" }, platform: "CPython 3.7.0.final.0" }
mongodb_1  | 2018-08-07T07:32:02.086+0000 I NETWORK  [conn4] end connection 172.18.0.3:34368 (0 connections now open)
mongodb_1  | 2018-08-07T07:35:10.378+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:34370 #5 (1 connection now open)
web_1      | 2018-08-07 07:35:10,378 - cert_viewer - INFO - Configured a file system certificate store with path=/etc/cert_data
mongodb_1  | 2018-08-07T07:35:10.395+0000 I NETWORK  [conn5] received client metadata from 172.18.0.3:34370 conn5: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.93-linuxkit-aufs" }, platform: "CPython 3.7.0.final.0" }
web_1      | /usr/local/lib/python3.7/site-packages/merkletools/__init__.py:7: UserWarning: sha3 is not working!
web_1      |   warn("sha3 is not working!")
web_1      | Traceback (most recent call last):
web_1      |   File "/cert-viewer/run.py", line 16, in <module>
web_1      |     main()
web_1      |   File "/cert-viewer/run.py", line 10, in main
web_1      |     configure_app(conf)
web_1      |   File "/cert-viewer/cert_viewer/__init__.py", line 56, in configure_app
web_1      |     views.add_rules(app, configuration)
web_1      |   File "/cert-viewer/cert_viewer/views/__init__.py", line 66, in add_rules
web_1      |     from cert_viewer.views.request_view import RequestView
web_1      |   File "/cert-viewer/cert_viewer/views/request_view.py", line 10, in <module>
web_1      |     from cert_viewer.notifier import Notifier
web_1      |   File "/cert-viewer/cert_viewer/notifier.py", line 58
web_1      |     **template_content=template_content, message=message,async=False)
web_1      |                                                                                                       ^
web_1      | SyntaxError: invalid syntax**
mongodb_1  | 2018-08-07T07:35:12.068+0000 I NETWORK  [conn5] end connection 172.18.0.3:34370 (0 connections now open)
cert-viewer_web_1 exited with code 1`

**Comment by hafsahabib-educator** [comment]
@kimdhamilton can you please help me here ?

**Comment by Haddadmj** [comment]
did u solve the problem ?

**Comment by kimdhamilton** [comment]
@hafsabukhary It looks like the error message is clear -- why don't you fix and submit a PR?

**Comment by jchartrand** [comment]
I think the problem is that 'async' became a reserved word in recent versions of Python (3.7, and with some backwards compatibility in 3.5 and 3.6), but the Mandrill package uses 'async' as one of it's argument names.  Maybe Mandrill could be updated, but I think it's only still in there for backwards compatibility as noted here (https://github.com/blockchain-certificates/cert-viewer/blob/master/README.md#notifications):

```
If you expose the 'certificate request' form, you may enable mandrill email alerts. This is mainly kept for backwards compatibility -- if you want to use this, you may choose to generalize or improve the notifier.py class.
```
So maybe it should just be removed?  If so, I'm happy to submit a PR (removing Mandrill is how I got the cert-viewer working).

**Comment by abder** [comment]
When  I used pyhton 3.6 rathar than 3.7 I solved the problem

**Comment by AramayisO** [comment]
As already mentioned, the issue is that `async` became a reserved word in version 3.7 of Python. If you're using Docker, you can resolve this by changing line 1 in cert-viewer/Dockerfile from`FROM python:3` to `FROM python:3.6`. Then just run `docker-compose build && docker-compose up` again. Should work then.
